services:
   app:
       build:
           context: .
       ports:
           - "8000:8000"
       command: >
        sh -c "python manage.py wait_for_db &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
       volumes:
        - ./:/app
       env_file:
           - .env
       environment:
         - RUNNING_IN_DOCKER=true
       depends_on:
           - db

   db:
       image: postgres:latest
       restart: always
       ports:
           - "5432:5432"
       env_file:
           - .env
       volumes:
         - my_db:/var/lib/postgresql/data

volumes:
  my_db:
